### ISSUE TITLE
How to fit into LEGO pieces?

### ISSUE THREAD

**Issue by weeberp** [BrownDogGadgets/CrazyCircuits#1]
I've seen that PCBs for mini Arduino, Teensy ... have no holes in the inside, so they can not fit into the standard lego bricks. These bricks should not have pins in the inside either. It is not like this?.
You would have to define these PCBs so that they have holes in them, or make a hole-only PCB so they would get underneath and raise this PCB (Well I'm not too sure about this second).
Thanks.

**Comment by Joshua-BrownDogGadgets** [comment]
Good questions.  

We made that design choice on purpose.  Due to the many small through hole pins on a NANO or TEENSY board we could not get things to line up with LEGO holes.  The exception to this is the ATTiny85 where we were able to get things worked out for both TH and SMT versions of the 85.

The way we use the NANO and TEENSY boards is to just slightly elevate the PCB with legos.  You can see that in many of our pictures.  Even using a few 1x2 or a couple of 1x8 thin LEGO strips is enough to  elevate the PCBs from any LEGO structure.  

https://github.com/BrownDogGadgets/CrazyCircuits/blob/master/Crazy%20Circuits%20Arduino.JPG

It's annoying, but it's the only way we could get things working.  Spacing just is way too difficult.

**Comment by weeberp** [comment]
OK, thanks, I see it better.
![crazy circuits arduino not right](https://cloud.githubusercontent.com/assets/4478762/26023894/b6075150-37c6-11e7-98f4-14fd0c575536.jpg)
![crazy circuits arduino right](https://cloud.githubusercontent.com/assets/4478762/26023895/b60869a0-37c6-11e7-8534-75fcd427dcdf.jpg)

**Comment by Joshua-BrownDogGadgets** [comment]
Bingo.  Just use a 1 or 2 stud wide brick.  That works just fine as as a base.  

For a couple of projects we also have them hanging off the sides of a brick board.  It really depends on your project.
